## YAML Template.
---
parameters:
    users_entity_subscriber.class: ACS\ACSPanelUsersBundle\Event\Subscribers\EntitySubscriber
    acl_logic_subscriber.class: ACS\ACSPanelUsersBundle\Event\Subscribers\AclLogicSubscriber

services:
    # Menu items added with event listener
    users_menu_subscriber:
        class: ACS\ACSPanelUsersBundle\Event\Subscribers\MenuSubscriber
        arguments: ['@event_dispatcher']
        tags:
            - {name: kernel.event_subscriber}

    # Entity subscribers
    users_entity_subscriber:
        class: %users_entity_subscriber.class%
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }

    # Entity subscribers
    users_acl_logic_subscriber:
        class: %acl_logic_subscriber.class%
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }

