ACS\ACSPanelUsersBundle\Entity\User:
    xml_root_name: user
    properties:
        id:
            expose: true
        firstname:
            expose: true
        lastname:
            expose: true
        uid:
            expose: true
        gid:
            expose: true
        child_users:
            exclude: true
        password:
            exclude: true
